FROM debian
ADD debian.list /etc/apt/sources.list.d/
RUN apt-get update && \
    apt-get -y upgrade && \
    apt -y install nginx && \
    apt-get clean && \
    rm -rf /var/www/* && \ 
    mkdir -p /var/www/Survival_Evolved.com/img && \
    chmod -R 754 /var/www/Survival_Evolved.com/ && \
    useradd ARK && groupadd BARKOV && usermod -a -G BARKOV ARK && \
    chown -R ARK:BARKOV /var/www/Survival_Evolved.com && \
    sed -i 's$/var/www/html/$/var/www/Survival_Evolved.com$g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user ARK/g' /etc/nginx/nginx.conf
ADD index.html /var/www/Survival_Evolved.com/
ADD img.jpg /var/www/Survival_Evolved.com/img/
CMD ["nginx", "-g", "daemon off;"]